### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by bmd007** [rsocket/rsocket-dart#20]
Any signs of this plugin working with web? 
I get 
````
Error: Unsupported operation: Socket constructor
    at Object.throw_ [as throw] (http://localhost:50672/dart_sdk.js:5080:11)
    at Socket._connect (http://localhost:50672/dart_sdk.js:60222:17)
    at Socket.connect (http://localhost:50672/dart_sdk.js:60205:26)
    at Object.connectRSocket (http://localhost:50672/packages/rsocket/duplex_connection.dart.lib.js:200:36)
    at rsocket_connector.RSocketConnector.create.connect (http://localhost:50672/packages/rsocket/rsocket_connector.dart.lib.js:89:34)
    at connect.next (<anonymous>)
    at runBody (http://localhost:50672/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:50672/dart_sdk.js:40691:7)
    at rsocket_connector.RSocketConnector.create.connect (http://localhost:50672/packages/rsocket/rsocket_connector.dart.lib.js:76:20)
    at Object.addName (http://localhost:50672/packages/dance_partner_finder/api_gateway_rsocket_client.dart.lib.js:40:60)
    at http://localhost:50672/packages/dance_partner_finder/dance_partner_finder_bloc.dart.lib.js:173:212
    at _RootZone.runUnary (http://localhost:50672/dart_sdk.js:40511:59)
    at _FutureListener.then.handleValue (http://localhost:50672/dart_sdk.js:35438:29)
    at handleValueCallback (http://localhost:50672/dart_sdk.js:35999:49)
    at _Future._propagateToListeners (http://localhost:50672/dart_sdk.js:36037:17)
    at [_completeWithValue] (http://localhost:50672/dart_sdk.js:35872:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50672/dart_sdk.js:35906:35)
    at Object._microtaskLoop (http://localhost:50672/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:50672/dart_sdk.js:40784:13)
    at http://localhost:50672/dart_sdk.js:36261:9
```
while trying to connect.

**Comment by bmd007** [comment]
ah, I just needed to get the latest version of the package from git instead of flutter.dev . Good stuff here
